sudo: required
language: python

python:
  - '3.6'

services:
  - docker

before_install:
  #- sudo apt-get update
  #- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - sudo rm -f /usr/local/bin/docker-compose

  - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  #commented out the above to see the docker-compose version as is on Travis and how
  #well it performs   
  - docker-compose --version
  - docker-compose build
  - docker-compose start
  - docker ps
